SELECT RI.FOOD_TYPE,RI.REST_ID,RI.REST_NAME,RI.FAVORITES FROM REST_INFO RI
WHERE RI.FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO AS RRI WHERE RI.FOOD_TYPE=RRI.FOOD_TYPE)
ORDER BY RI.FOOD_TYPE DESC
;