-- 코드를 입력하세요
SELECT UU.USER_ID,UU.NICKNAME,SUM(UB.PRICE)TOTAL_SALES FROM USED_GOODS_BOARD UB
INNER JOIN USED_GOODS_USER UU ON UB.WRITER_ID = UU.USER_ID
WHERE UB.STATUS = "DONE"
GROUP BY WRITER_ID
HAVING SUM(UB.PRICE)>=700000
ORDER BY TOTAL_SALES
;